let i = 0

export default [
    { key: i++, code: 'USD', symbol: '&#36;', name: 'United States Dollar' },
    { key: i++, code: 'CAD', symbol: '&#36;', name: 'Canadian Dollar' },
    { key: i++, code: 'GBP', symbol: '&#163;', name: 'United Kingdom Pound' },
    { key: i++, code: 'ALL', symbol: '&#76;&#101;&#107;', name: 'Albania Lek' },
    { key: i++, code: 'AFN', symbol: '&#1547;', name: 'Afghanistan Afghani' },
    { key: i++, code: 'ARS', symbol: '&#36;', name: 'Argentina Peso' },
    { key: i++, code: 'AWG', symbol: '&#402;', name: 'Aruba Guilder' },
    { key: i++, code: 'AUD', symbol: '&#36;', name: 'Australian Dollar' },
    { key: i++, code: 'AZN', symbol: '&#8380;', name: 'Azerbaijan Manat' },
    { key: i++, code: 'BSD', symbol: '&#36;', name: 'Bahamas Dollar' },
    { key: i++, code: 'BBD', symbol: '&#36;', name: 'Barbados Dollar' },
    { key: i++, code: 'BYN', symbol: '&#66;&#114;', name: 'Belarus Ruble' },
    { key: i++, code: 'BZD', symbol: '&#66;&#90;&#36;', name: 'Belize Dollar' },
    { key: i++, code: 'BMD', symbol: '&#36;', name: 'Bermuda Dollar' },
    { key: i++, code: 'BOB', symbol: '&#36;&#98;', name: 'Bolivia Bolíviano' },
    {
        key: i++,
        code: 'BAM',
        symbol: '&#75;&#77;',
        name: 'Bosnia and Herzegovina Convertible Marka'
    },
    { key: i++, code: 'BWP', symbol: '&#80;', name: 'Botswana Pula' },
    { key: i++, code: 'BGN', symbol: '&#1083;&#1074;', name: 'Bulgaria Lev' },
    { key: i++, code: 'BRL', symbol: '&#82;&#36;', name: 'Brazil Real' },
    {
        key: i++,
        code: 'BND',
        symbol: '&#36;',
        name: 'Brunei Darussalam Dollar'
    },
    { key: i++, code: 'KHR', symbol: '&#6107;', name: 'Cambodia Riel' },
    { key: i++, code: 'CAD', symbol: '&#36;', name: 'Canadian Dollar' },
    { key: i++, code: 'KYD', symbol: '&#36;', name: 'Cayman Islands Dollar' },
    { key: i++, code: 'CLP', symbol: '&#36;', name: 'Chile Peso' },
    { key: i++, code: 'CNY', symbol: '&#165;', name: 'China Yuan Renminbi' },
    { key: i++, code: 'COP', symbol: '&#36;', name: 'Colombia Peso' },
    { key: i++, code: 'CRC', symbol: '&#8353;', name: 'Costa Rica Colon' },
    { key: i++, code: 'HRK', symbol: '&#107;&#110;', name: 'Croatia Kuna' },
    { key: i++, code: 'CUP', symbol: '&#8369;', name: 'Cuba Peso' },
    {
        key: i++,
        code: 'CZK',
        symbol: '&#75;&#269;',
        name: 'Czech Republic Koruna'
    },
    { key: i++, code: 'DKK', symbol: '&#107;&#114;', name: 'Denmark Krone' },
    {
        key: i++,
        code: 'DOP',
        symbol: '&#82;&#68;&#36;',
        name: 'Dominican Republic Peso'
    },
    { key: i++, code: 'XCD', symbol: '&#36;', name: 'East Caribbean Dollar' },
    { key: i++, code: 'EGP', symbol: '&#163;', name: 'Egypt Pound' },
    { key: i++, code: 'SVC', symbol: '&#36;', name: 'El Salvador Colon' },
    { key: i++, code: 'EUR', symbol: '&#8364;', name: 'Euro Member Countries' },
    {
        key: i++,
        code: 'FKP',
        symbol: '&#163;',
        name: 'Falkland Islands (Malvinas) Pound'
    },
    { key: i++, code: 'FJD', symbol: '&#36;', name: 'Fiji Dollar' },
    { key: i++, code: 'GHS', symbol: '&#162;', name: 'Ghana Cedi' },
    { key: i++, code: 'GIP', symbol: '&#163;', name: 'Gibraltar Pound' },
    { key: i++, code: 'GTQ', symbol: '&#81;', name: 'Guatemala Quetzal' },
    { key: i++, code: 'GGP', symbol: '&#163;', name: 'Guernsey Pound' },
    { key: i++, code: 'GYD', symbol: '&#36;', name: 'Guyana Dollar' },
    { key: i++, code: 'HNL', symbol: '&#76;', name: 'Honduras Lempira' },
    { key: i++, code: 'HKD', symbol: '&#36;', name: 'Hong Kong Dollar' },
    { key: i++, code: 'HUF', symbol: '&#70;&#116;', name: 'Hungary Forint' },
    { key: i++, code: 'ISK', symbol: '&#107;&#114;', name: 'Iceland Krona' },
    { key: i++, code: 'INR', symbol: '&#8377;', name: 'India Rupee' },
    { key: i++, code: 'IDR', symbol: '&#82;&#112;', name: 'Indonesia Rupiah' },
    { key: i++, code: 'IRR', symbol: '&#65020;', name: 'Iran Rial' },
    { key: i++, code: 'IMP', symbol: '&#163;', name: 'Isle of Man Pound' },
    { key: i++, code: 'ILS', symbol: '&#8362;', name: 'Israel Shekel' },
    { key: i++, code: 'JMD', symbol: '&#74;&#36;', name: 'Jamaica Dollar' },
    { key: i++, code: 'JPY', symbol: '&#165;', name: 'Japan Yen' },
    { key: i++, code: 'JEP', symbol: '&#163;', name: 'Jersey Pound' },
    {
        key: i++,
        code: 'KZT',
        symbol: '&#1083;&#1074;',
        name: 'Kazakhstan Tenge'
    },
    { key: i++, code: 'KPW', symbol: '&#8361;', name: 'Korea (North) Won' },
    { key: i++, code: 'KRW', symbol: '&#8361;', name: 'Korea (South) Won' },
    { key: i++, code: 'KGS', symbol: '&#1083;&#1074;', name: 'Kyrgyzstan Som' },
    { key: i++, code: 'LAK', symbol: '&#8365;', name: 'Laos Kip' },
    { key: i++, code: 'LBP', symbol: '&#163;', name: 'Lebanon Pound' },
    { key: i++, code: 'LRD', symbol: '&#36;', name: 'Liberia Dollar' },
    {
        key: i++,
        code: 'MKD',
        symbol: '&#1076;&#1077;&#1085;',
        name: 'Macedonia Denar'
    },
    { key: i++, code: 'MYR', symbol: '&#82;&#77;', name: 'Malaysia Ringgit' },
    { key: i++, code: 'MUR', symbol: '&#8360;', name: 'Mauritius Rupee' },
    { key: i++, code: 'MXN', symbol: '&#36;', name: 'Mexico Peso' },
    { key: i++, code: 'MNT', symbol: '&#8366;', name: 'Mongolia Tughrik' },
    { key: i++, code: 'MZN', symbol: '&#77;&#84;', name: 'Mozambique Metical' },
    { key: i++, code: 'NAD', symbol: '&#36;', name: 'Namibia Dollar' },
    { key: i++, code: 'NPR', symbol: '&#8360;', name: 'Nepal Rupee' },
    {
        key: i++,
        code: 'ANG',
        symbol: '&#402;',
        name: 'Netherlands Antilles Guilder'
    },
    { key: i++, code: 'NZD', symbol: '&#36;', name: 'New Zealand Dollar' },
    { key: i++, code: 'NIO', symbol: '&#67;&#36;', name: 'Nicaragua Cordoba' },
    { key: i++, code: 'NGN', symbol: '&#8358;', name: 'Nigeria Naira' },
    { key: i++, code: 'NOK', symbol: '&#107;&#114;', name: 'Norway Krone' },
    { key: i++, code: 'OMR', symbol: '&#65020;', name: 'Oman Rial' },
    { key: i++, code: 'PKR', symbol: '&#8360;', name: 'Pakistan Rupee' },
    { key: i++, code: 'PAB', symbol: '&#66;&#47;&#46;', name: 'Panama Balboa' },
    { key: i++, code: 'PYG', symbol: '&#71;&#115;', name: 'Paraguay Guarani' },
    { key: i++, code: 'PEN', symbol: '&#83;&#47;&#46;', name: 'Peru Sol' },
    { key: i++, code: 'PHP', symbol: '&#8369;', name: 'Philippines Piso' },
    { key: i++, code: 'PLN', symbol: '&#122;&#322;', name: 'Poland Zloty' },
    { key: i++, code: 'QAR', symbol: '&#65020;', name: 'Qatar Riyal' },
    {
        key: i++,
        code: 'RON',
        symbol: '&#108;&#101;&#105;',
        name: 'Romania Leu'
    },
    { key: i++, code: 'RUB', symbol: '&#8381;', name: 'Russia Ruble' },
    { key: i++, code: 'SHP', symbol: '&#163;', name: 'Saint Helena Pound' },
    { key: i++, code: 'SAR', symbol: '&#65020;', name: 'Saudi Arabia Riyal' },
    {
        key: i++,
        code: 'RSD',
        symbol: '&#1044;&#1080;&#1085;&#46;',
        name: 'Serbia Dinar'
    },
    { key: i++, code: 'SCR', symbol: '&#8360;', name: 'Seychelles Rupee' },
    { key: i++, code: 'SGD', symbol: '&#36;', name: 'Singapore Dollar' },
    { key: i++, code: 'SBD', symbol: '&#36;', name: 'Solomon Islands Dollar' },
    { key: i++, code: 'SOS', symbol: '&#83;', name: 'Somalia Shilling' },
    { key: i++, code: 'ZAR', symbol: '&#82;', name: 'South Africa Rand' },
    { key: i++, code: 'LKR', symbol: '&#8360;', name: 'Sri Lanka Rupee' },
    { key: i++, code: 'SEK', symbol: '&#107;&#114;', name: 'Sweden Krona' },
    {
        key: i++,
        code: 'CHF',
        symbol: '&#67;&#72;&#70;',
        name: 'Switzerland Franc'
    },
    { key: i++, code: 'SRD', symbol: '&#36;', name: 'Suriname Dollar' },
    { key: i++, code: 'SYP', symbol: '&#163;', name: 'Syria Pound' },
    {
        key: i++,
        code: 'TWD',
        symbol: '&#78;&#84;&#36;',
        name: 'Taiwan New Dollar'
    },
    { key: i++, code: 'THB', symbol: '&#3647;', name: 'Thailand Baht' },
    {
        key: i++,
        code: 'TTD',
        symbol: '&#84;&#84;&#36;',
        name: 'Trinidad and Tobago Dollar'
    },
    { key: i++, code: 'TRY', symbol: '&#8378;', name: 'Turcode Lira' },
    { key: i++, code: 'TVD', symbol: '&#36;', name: 'Tuvalu Dollar' },
    { key: i++, code: 'UAH', symbol: '&#8372;', name: 'Ukraine Hryvnia' },
    { key: i++, code: 'GBP', symbol: '&#163;', name: 'United Kingdom Pound' },
    { key: i++, code: 'USD', symbol: '&#36;', name: 'United States Dollar' },
    { key: i++, code: 'UYU', symbol: '&#36;&#85;', name: 'Uruguay Peso' },
    { key: i++, code: 'UZS', symbol: '&#1083;&#1074;', name: 'Uzbekistan Som' },
    { key: i++, code: 'VEF', symbol: '&#66;&#115;', name: 'Venezuela Bolívar' },
    { key: i++, code: 'VND', symbol: '&#8363;', name: 'Viet Nam Dong' },
    { key: i++, code: 'YER', symbol: '&#65020;', name: 'Yemen Rial' },
    { key: i++, code: 'ZWD', symbol: '&#90;&#36;', name: 'Zimbabwe Dollar' }
]
