# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BudgetTracker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BudgetTracker
  pod 'GoogleSignIn'
  pod 'Firebase/Core'
  
  target 'BudgetTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BudgetTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
